name: Pull Request Target

permissions:
  contents: read

on:
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run:
          echo ${{ secrets.GITHUB_TOKEN }} 
