name: Update Website

on:
  push:
        
jobs:
  clang_www:
    name: Update clang.llvm.org
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get install ninja-build python3-sphinx
      - name: Download source code
        uses: llvm/actions/get-llvm-project-src@master
        with:
          ref: ${{ github.sha }}
          repo: ${{ github.repository }}
      - name: Build documentation
        run: |
          mkdir build
          cd build
          cmake ../llvm -G Ninja -DLLVM_ENABLE_PROJECTS=clang -DLLVM_ENABLE_SPHINX=ON -DSPHINX_WARNINGS_AS_ERRORS=OFF
          ninja docs-clang-html

      - name: Clone clang-www
        run: git clone https://${WWW_TOKEN}@github.com/llvmbot/clang-www
        env:
          WWW_TOKEN: ${{ secrets.WWW_TOKEN }}

      - name: Update local copy of clang-www
        working-directory: ./clang-www 
        run: |
          git rm -r *
          cp -R ../clang/www/* .
          mkdir -p docs
          cp -R ../build/tools/clang/docs/html/* docs/

      - name: Push changes to clang-www repo
        working-directory: ./clang-www
        run: |
          git config --global user.name "llvmbot"
          git config --global user.email "llvmbot@llvm.org"
          git add *
          git commit -a -m "Update documentation from commit $GITHUB_SHA"
          git push origin master:master
